import * as THREE from 'three';
const V=a=>new THREE.Vector3(...a);
function connectorGeometry(){const shape=new THREE.Shape();const w=.0179,d=.0039;shape.moveTo(-w/2,-d/2);shape.lineTo(w/2,-d/2);shape.lineTo(w/2,d/2);shape.lineTo(-w/2,d/2);shape.closePath();for(let i=0;i<7;i++){const x=(i-3)*.0025,r=.00046,p=new THREE.Path();p.moveTo(x-r,-r);p.lineTo(x-r,r);p.lineTo(x+r,r);p.lineTo(x+r,-r);p.closePath();shape.holes.push(p)}return new THREE.ExtrudeGeometry(shape,{depth:.0065,bevelEnabled:false}).rotateX(-Math.PI/2).translate(0,-.0065,0)}
function mergedTubes(curves){const geometries=curves.map(c=>new THREE.TubeGeometry(c,40,.00034,5,false));let positions=[],normals=[],indices=[],offset=0;for(const g of geometries){positions.push(...g.attributes.position.array);normals.push(...g.attributes.normal.array);indices.push(...Array.from(g.index.array,i=>i+offset));offset+=g.attributes.position.count;g.dispose()}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));g.setAttribute('normal',new THREE.Float32BufferAttribute(normals,3));g.setIndex(indices);return g;}
export function parkedCableEnd(c){return V(c.parkedEnd||c.end).setY(c.parkedEnd?c.parkedEnd[1]:.061);}
export function cableRoute(c,connected,lift=0){const start=V(c.start),end=connected?V(c.end).add(new THREE.Vector3(0,lift,0)):parkedCableEnd(c);const p1=start.clone().add(new THREE.Vector3(0,.007,0));const inner=start.clone();inner.y=.029;inner.x*=.35;inner.z*=.35;const mid=inner.clone();mid.y=connected?.055+lift*.4:.064;const p4=end.clone().add(new THREE.Vector3(0,-.008,0));if(!connected)return [start,p1,inner,new THREE.Vector3(end.x,end.y-.008,end.z),end];if(c.via)return [start,p1,...c.via.map(a=>V(a).add(new THREE.Vector3(0,lift*.4,0))),p4,end];return [start,p1,inner,mid,p4,end];}
export function ribbonTangents(c,connected){const start=V(c.tangent).normalize(),end=connected?V(c.endTangent||c.tangent).normalize():start.clone();if(start.dot(end)<0)end.negate();return {start,end};}
export function ribbonCurves(c,connected,lift=0){const points=cableRoute(c,connected,lift),center=new THREE.CatmullRomCurve3(points,false,'centripetal'),{start,end}=ribbonTangents(c,connected),from=Math.atan2(start.z,start.x),delta=Math.atan2(start.x*end.z-start.z*end.x,start.dot(end));class Lane extends THREE.Curve{constructor(lane){super();this.lane=lane}getPoint(t,target=new THREE.Vector3()){center.getPoint(t,target);const eased=t*t*(3-2*t),angle=from+delta*eased,edge=Math.max(0,1-t/.18,1-(1-t)/.18),pitch=.001+.0015*edge;return target.addScaledVector(new THREE.Vector3(Math.cos(angle),0,Math.sin(angle)),this.lane*pitch)}}return Array.from({length:7},(_,i)=>new Lane(i-3));}
export function createCables(data){const group=new THREE.Group();group.name='group_sensor-cables';group.userData={groupId:'sensor-cables',displayName:'7P JST-XH sensorkabels'};const head=connectorGeometry(),white=new THREE.MeshStandardMaterial({color:0xe7e5da,roughness:.65}),wireMaterial=new THREE.MeshStandardMaterial({color:0xded9d4,roughness:.8});const cables=[];for(const c of data){const node=new THREE.Group();node.name=c.id;node.userData={groupId:'sensor-cables',displayName:'7P JST-XH ribbonkabel',sourceName:c.id,cableId:c.id};const wire=new THREE.Mesh(new THREE.BufferGeometry(),wireMaterial),a=new THREE.Mesh(head,white),b=new THREE.Mesh(head,white);node.add(wire,a,b);group.add(node);cables.push({data:c,node,wire,a,b});}let last='';function update(connected,lift){const key=connected+':'+lift;if(key===last)return;last=key;for(const c of cables){const points=cableRoute(c.data,connected,lift),{start:tangent,end:endTangent}=ribbonTangents(c.data,connected);const curves=ribbonCurves(c.data,connected,lift);c.wire.geometry.dispose();c.wire.geometry=mergedTubes(curves);c.a.position.copy(points[0]);c.a.quaternion.setFromRotationMatrix(new THREE.Matrix4().makeBasis(tangent,new THREE.Vector3(0,1,0),new THREE.Vector3().crossVectors(tangent,new THREE.Vector3(0,1,0))));const normal=connected?new THREE.Vector3(0,-1,0):new THREE.Vector3(0,1,0);c.b.position.copy(points.at(-1));c.b.quaternion.setFromRotationMatrix(new THREE.Matrix4().makeBasis(endTangent,normal,new THREE.Vector3().crossVectors(endTangent,normal)));c.node.userData.connectionState=connected?'sensor-and-pcb':'sensor-only';} }update(true,0);return {group,cables,update};}
