import {xtParts} from './connector-geometry.mjs';
import * as THREE from 'three';
const V=a=>new THREE.Vector3(...a),Y=new THREE.Vector3(0,1,0);
function socket(count,pitch,width,depth,height,color){const shape=new THREE.Shape();shape.moveTo(-width/2,-depth/2);shape.lineTo(width/2,-depth/2);shape.lineTo(width/2,depth/2);shape.lineTo(-width/2,depth/2);shape.closePath();for(let i=0;i<count;i++){const h=new THREE.Path(),x=(i-(count-1)/2)*pitch,r=count===2?.00125:.00045;h.moveTo(x-r,-r);h.lineTo(x-r,r);h.lineTo(x+r,r);h.lineTo(x+r,-r);h.closePath();shape.holes.push(h)}const g=new THREE.ExtrudeGeometry(shape,{depth:height,bevelEnabled:false}).rotateX(Math.PI/2);return new THREE.Mesh(g,new THREE.MeshStandardMaterial({color,roughness:.7}));}
export function harnessWireRadius(c){if(c.connectorType==='XT60')return .0011;if(c.connectorType==='XT30')return .0009;return c.kind==='dupont'?.00040:.00060}
function tube(points,r,smooth=false){if(smooth)return new THREE.TubeGeometry(new THREE.CatmullRomCurve3(points,false,'centripetal'),48,r,8,false);const path=new THREE.CurvePath();for(let i=1;i<points.length;i++)path.add(new THREE.LineCurve3(points[i-1],points[i]));return new THREE.TubeGeometry(path,Math.max(32,points.length*10),r,7,false)}
export function harnessRoutes(c,state={}){const lift=state.pcbLift||0,mcLift=state.looseController===c.controller?.030:0;if(c.kind==='motor'){const connected=state.assembled||state.outputs?.includes(c.controller);return c.starts.map((p,i)=>{const s=V(p),end=connected?V(c.ends[i]):s.clone().multiply(new THREE.Vector3(.6,1,.6)).add(V([i*.004,.012,-i*.004]));const a=s.clone();a.x*=.72;a.z*=.72;const rise=a.clone();rise.y=.039+i*.0015;const b=rise.clone();b.y=.047+i*.0015;if(!connected)return [s,a,rise,b,end];const approach=end.clone().addScaledVector(V(c.outward),.010);const high=approach.clone();high.y=b.y;const settle=high.clone().lerp(approach,.55);return [s,a,rise,b,high,settle,approach,end]})}
 if(c.kind==='battery'){return c.starts.map((p,i)=>{const s=V(p).addScaledVector(Y,lift),e=V(c.end).addScaledVector(Y,lift).addScaledVector(V(c.endTangent),(c.swapConnectorPolarity?.5-i:i-.5)*.0072),a=s.clone().addScaledVector(Y,-.007),b=V(c.routeWaypoint||[-.042,.070,-.048]).addScaledVector(Y,lift).addScaledVector(V(c.endTangent),(c.swapConnectorPolarity?.5-i:i-.5)*.009);return [s,a,b,e.clone().addScaledVector(new THREE.Vector3(Math.SQRT1_2,0,Math.SQRT1_2),-.008),e]})}
 if(['switch','battery'].includes(c.kind)){return c.starts.map((p,i)=>{const connected=state.assembled||state.switchConnections===undefined||state.switchConnections.includes(c.switch);const s=V(p).addScaledVector(Y,lift),e=V(c.end).addScaledVector(Y,lift+(connected?0:-.016)).addScaledVector(V(c.endTangent),(i-.5)*.005),a=s.clone().addScaledVector(Y,-.004-i*.009),b=e.clone().addScaledVector(Y,-.008-i*.004),side=new THREE.Vector3(-(e.z-s.z),0,e.x-s.x).normalize(),mid=a.clone().lerp(b,.5).addScaledVector(side,(i===0?1:-1)*.006);return [s,a,mid,b,e]})}
 if(c.kind==='power'){const connected=state.assembled||state.xt30;let plug=connected?V(c.end).addScaledVector(Y,lift):V(c.parkedEnd||c.end).setY(c.parkedEnd?c.parkedEnd[1]:.062);if(!connected)plug.y+=mcLift;const end=plug.clone().addScaledVector(Y,connected?.0015:0),startPair=c.starts.map(p=>V(p).addScaledVector(Y,mcLift)),start=startPair[0].clone().add(startPair[1]).multiplyScalar(.5),lane=startPair[0].clone().sub(start).normalize().multiplyScalar(.0025),mid=start.clone().lerp(end,.62);mid.y=Math.max(start.y,end.y)-.007;const approach=end.clone().addScaledVector(Y,-.005),center=new THREE.CatmullRomCurve3([start,start.clone().addScaledVector(V(c.outward),.008).addScaledVector(Y,.003),mid,approach,end],false,'centripetal'),n=97,ts=Array.from({length:n},(_,i)=>i/(n-1)),tangents=ts.map(t=>center.getTangent(t).normalize()),sides=[lane.clone().addScaledVector(tangents[0],-lane.dot(tangents[0])).normalize()];for(let j=1;j<n;j++)sides.push(sides[j-1].clone().applyQuaternion(new THREE.Quaternion().setFromUnitVectors(tangents[j-1],tangents[j])).normalize());const desired=connected?V(c.endTangent).multiplyScalar(c.swapConnectorPolarity?.0025:-.0025):lane,axis=tangents.at(-1),cross=sides.at(-1).clone().cross(desired.clone().normalize()),twist=Math.atan2(axis.dot(cross),sides.at(-1).dot(desired.clone().normalize()));return [0,1].map(i=>ts.map((t,j)=>{const eased=t*t*(3-2*t),offset=sides[j].clone().applyAxisAngle(tangents[j],twist*eased).multiplyScalar(.0025);if(i)offset.negate();return center.getPoint(t).add(offset)}))}
 const start=V(c.start).addScaledVector(Y,mcLift),end=V(c.end).addScaledVector(Y,lift),slit=V(c.slit).addScaledVector(Y,lift),tan=V(c.endTangent),st=V(c.startTangent);const common=V(c.routeTangent||c.endTangent);return Array.from({length:6},(_,i)=>{const k=i-2.5,s=start.clone().addScaledVector(st,k*.00254),e=end.clone().addScaledVector(tan,k*.00254),entry=slit.clone().addScaledVector(tan,k*.00254);entry.y-=.008;const exit=entry.clone();exit.y=slit.y+.008;const pre=start.clone().addScaledVector(Y,.004).addScaledVector(common,k*.00254);const lane=pre.clone().lerp(entry,.46);lane.y=entry.y-.010;const shoulder=entry.clone().lerp(exit,.42);shoulder.y=slit.y-.002;return [s,pre,lane,entry,shoulder,exit,e.clone().addScaledVector(Y,.004),e]});}

function xtHead(type,gender,swap=false){const g=new THREE.Group();for(const p of xtParts(type,gender))g.add(new THREE.Mesh(p.geometry,new THREE.MeshStandardMaterial({color:p.role==='housing'?0xdda40b:p.role==='redSleeve'?(swap?0x25282d:0xc62b2c):p.role==='blackSleeve'?(swap?0xc62b2c:0x25282d):0xbb8c32,roughness:.42,metalness:p.role==='contact'?.8:0})));return g;}
export function createHarness(data){const group=new THREE.Group();group.name='harness';const items=data.map(c=>{const node=new THREE.Group();node.name='group_'+c.id;node.userData={groupId:c.id,sourceName:c.id,category:'mechanical'};group.add(node);const count=c.kind==='dupont'?6:2,wires=[];for(let i=0;i<count;i++){const wire=new THREE.Mesh(new THREE.BufferGeometry(),new THREE.MeshStandardMaterial({color:c.kind==='dupont'?[0x766247,0xae463d,0xda8431,0xd9bd4e,0x3e9568,0x436ead][i]:i===0?0xc62b2c:0x25282d,roughness:.76}));wire.name=c.id+'-'+i;wire.userData={groupId:c.id,sourceName:c.kind==='motor'?(i?'Zwarte motordraad':'Rode motordraad'):c.kind==='power'?(i?'Zwarte voedingsdraad':'Rode voedingsdraad'):'Dupont ader '+(i+1)};node.add(wire);wires.push(wire)}let heads=[];if(c.kind==='dupont'){heads=[socket(6,.00254,.01524,.00254,.008,0x25282d),socket(6,.00254,.01524,.00254,.008,0x25282d)]}else if(['power','switch','battery'].includes(c.kind)){heads=[xtHead(c.connectorType||'XT30',c.gender||'female',c.swapConnectorPolarity)]}for(const h of heads){h.userData={groupId:c.id,sourceName:c.kind==='dupont'?'6P female Dupont':(c.connectorType||'XT30')+' '+(c.gender||'female')+' kabelstekker'};h.traverse(n=>{n.userData={...h.userData}});node.add(h)}return {data:c,node,wires,heads}});let previous='';function orient(head,pos,tangent,axis=Y){head.position.copy(pos);const x=V(tangent).normalize();head.quaternion.setFromRotationMatrix(new THREE.Matrix4().makeBasis(x,axis,new THREE.Vector3().crossVectors(x,axis)))}
 function update(state={}){const key=JSON.stringify(state);if(key===previous)return;previous=key;for(const item of items){const c=item.data,routes=harnessRoutes(c,state);routes.forEach((p,i)=>{item.wires[i].geometry.dispose();item.wires[i].geometry=tube(p,harnessWireRadius(c),['switch','battery','motor','dupont'].includes(c.kind))});if(c.kind==='dupont'){const a=routes[0][0].clone().add(routes[5][0]).multiplyScalar(.5),b=routes[0].at(-1).clone().add(routes[5].at(-1)).multiplyScalar(.5);orient(item.heads[0],a,c.startTangent);orient(item.heads[1],b,c.endTangent)}else if(['power','switch','battery'].includes(c.kind)){let pos=routes[0].at(-1).clone().add(routes[1].at(-1)).multiplyScalar(.5),tangent=c.endTangent;if(c.kind==='power'){const connected=state.assembled||state.xt30;pos=connected?V(c.end).addScaledVector(Y,state.pcbLift||0):V(c.parkedEnd||c.end).setY(c.parkedEnd?c.parkedEnd[1]:.062);if(!connected){pos.y+=state.looseController===c.controller?.030:0;tangent=V(c.endTangent).negate();}}orient(item.heads[0],pos,tangent,c.kind==='battery'?new THREE.Vector3(Math.SQRT1_2,0,Math.SQRT1_2):Y)}}}
 update({assembled:true});return {group,items,update};}
