import * as THREE from 'three';
const V=a=>new THREE.Vector3(...a),Y=new THREE.Vector3(0,1,0);
function socket(count,pitch,width,depth,height,color){const shape=new THREE.Shape();shape.moveTo(-width/2,-depth/2);shape.lineTo(width/2,-depth/2);shape.lineTo(width/2,depth/2);shape.lineTo(-width/2,depth/2);shape.closePath();for(let i=0;i<count;i++){const h=new THREE.Path(),x=(i-(count-1)/2)*pitch,r=count===2?.00125:.00045;h.moveTo(x-r,-r);h.lineTo(x-r,r);h.lineTo(x+r,r);h.lineTo(x+r,-r);h.closePath();shape.holes.push(h)}const g=new THREE.ExtrudeGeometry(shape,{depth:height,bevelEnabled:false}).rotateX(Math.PI/2);return new THREE.Mesh(g,new THREE.MeshStandardMaterial({color,roughness:.7}));}
function tube(points,r){const path=new THREE.CurvePath();for(let i=1;i<points.length;i++)path.add(new THREE.LineCurve3(points[i-1],points[i]));return new THREE.TubeGeometry(path,Math.max(32,points.length*10),r,7,false)}
export function harnessRoutes(c,state={}){const lift=state.pcbLift||0,mcLift=state.looseController===c.controller?.030:0;if(c.kind==='motor'){const connected=state.assembled||state.outputs?.includes(c.controller);return c.starts.map((p,i)=>{const s=V(p),end=connected?V(c.ends[i]):s.clone().multiply(new THREE.Vector3(.6,1,.6)).add(V([i*.004,.012,-i*.004]));const a=s.clone();a.x*=.72;a.z*=.72;const b=a.clone();b.y=.047+i*.0015;if(!connected)return [s,a,b,end];const approach=end.clone().addScaledVector(V(c.outward),.010);const high=approach.clone();high.y=b.y;return [s,a,b,high,approach,end]})}
 if(c.kind==='power'){const connected=state.assembled||state.xt30;const tangent=V(c.endTangent);let end=connected?V(c.end).addScaledVector(Y,lift):V(c.starts[0]).add(V([-.010,.012,-.010]));if(!connected)end.y+=mcLift;return c.starts.map((p,i)=>{const s=V(p).addScaledVector(Y,mcLift),a=s.clone().addScaledVector(V(c.outward),.007),e=end.clone().addScaledVector(tangent,(i-.5)*.005),b=a.clone().lerp(e,.55);b.y=Math.max(a.y,e.y)-.002;return [s,a,b,e.clone().addScaledVector(Y,-.006),e]})}
 const start=V(c.start).addScaledVector(Y,mcLift),end=V(c.end).addScaledVector(Y,lift),slit=V(c.slit).addScaledVector(Y,lift),tan=V(c.endTangent),st=V(c.startTangent);return Array.from({length:6},(_,i)=>{const k=i-2.5,s=start.clone().addScaledVector(st,k*.00254),e=end.clone().addScaledVector(tan,k*.00254),entry=slit.clone().addScaledVector(tan,k*.00105);entry.y-=.008;const exit=entry.clone();exit.y=slit.y+.008;const pre=s.clone().addScaledVector(Y,.004);return [s,pre,entry,exit,e.clone().addScaledVector(Y,.004),e]});}
export function createHarness(data){const group=new THREE.Group();group.name='harness';const items=data.map(c=>{const node=new THREE.Group();node.name='group_'+c.id;node.userData={groupId:c.id,sourceName:c.id,category:'mechanical'};group.add(node);const count=c.kind==='dupont'?6:2,wires=[];for(let i=0;i<count;i++){const wire=new THREE.Mesh(new THREE.BufferGeometry(),new THREE.MeshStandardMaterial({color:c.kind==='dupont'?[0x766247,0xae463d,0xda8431,0xd9bd4e,0x3e9568,0x436ead][i]:i===0?0xc62b2c:0x25282d,roughness:.76}));wire.name=c.id+'-'+i;wire.userData={groupId:c.id,sourceName:c.kind==='motor'?(i?'Zwarte motordraad':'Rode motordraad'):c.kind==='power'?(i?'Zwarte voedingsdraad':'Rode voedingsdraad'):'Dupont ader '+(i+1)};node.add(wire);wires.push(wire)}let heads=[];if(c.kind==='dupont'){heads=[socket(6,.00254,.01524,.00254,.008,0x25282d),socket(6,.00254,.01524,.00254,.008,0x25282d)]}else if(c.kind==='power'){const head=socket(2,.005,.0087,.005,.008,0xd6ae29);head.geometry.rotateX(Math.PI);heads=[head]}for(const h of heads){h.userData={groupId:c.id,sourceName:c.kind==='dupont'?'6P female Dupont':'XT30 kabelstekker'};node.add(h)}return {data:c,node,wires,heads}});let previous='';function orient(head,pos,tangent){head.position.copy(pos);const x=V(tangent).normalize();head.quaternion.setFromRotationMatrix(new THREE.Matrix4().makeBasis(x,Y,new THREE.Vector3().crossVectors(x,Y)))}
 function update(state={}){const key=JSON.stringify(state);if(key===previous)return;previous=key;for(const item of items){const c=item.data,routes=harnessRoutes(c,state);routes.forEach((p,i)=>{item.wires[i].geometry.dispose();item.wires[i].geometry=tube(p,c.kind==='dupont'?.00040:.00060)});if(c.kind==='dupont'){const a=routes[0][0].clone().add(routes[5][0]).multiplyScalar(.5),b=routes[0].at(-1).clone().add(routes[5].at(-1)).multiplyScalar(.5);orient(item.heads[0],a,c.startTangent);orient(item.heads[1],b,c.endTangent)}else if(c.kind==='power'){orient(item.heads[0],routes[0].at(-1).clone().add(routes[1].at(-1)).multiplyScalar(.5),c.endTangent)}}}
 update({assembled:true});return {group,items,update};}
